### ISSUE TITLE
sonatype-staging is a not an existing directory

### ISSUE THREAD

**Issue by ghostbuster91** [sbt/sbt-ci-release#227]
This happens when the key or the key passphrase was incorrect. 

```
2022-02-05 19:12:06.[162](https://github.com/ghostbuster91/scalafix-unified/runs/5079515519?check_suite_focus=true#step:4:162)Z  info [SonatypeClient] Creating a staging repository in profile io.github.*** with a description key: [sbt-sonatype] root 0.0.1  - (SonatypeClient.scala:126)
2022-02-05 19:12:06.246Z  info [SonatypeService] No previous staging repository for [sbt-sonatype] root 0.0.1 was found  - (SonatypeService.scala:99)
2022-02-05 19:12:10.034Z  info [SonatypeClient] Created successfully: iogithub***-1011  - (SonatypeClient.scala:139)
2022-02-05 19:12:10.052Z error [Sonatype] 
java.io.IOException: Supplied file /home/runner/work/scalafix-unified/scalafix-unified/target/sonatype-staging/0.0.1 is a not an existing directory!
	at org.sonatype.spice.zapper.fs.AbstractDirectory.<init>(AbstractDirectory.java:32)
	at org.sonatype.spice.zapper.fs.DirectoryIOSource.<init>(DirectoryIOSource.java:68)
	at org.sonatype.spice.zapper.fs.DirectoryIOSource.<init>(DirectoryIOSource.java:59)
	at org.sonatype.spice.zapper.fs.DirectoryIOSource.<init>(DirectoryIOSource.java:50)
	at xerial.sbt.sonatype.SonatypeClient.$anonfun$uploadBundle$2(SonatypeClient.scala:284)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
```

If we scroll up the logs we can notice that the key was imported but the provided base64 input was invalid due to (https://github.com/sbt/sbt-ci-release/issues/226)

```
Running ci-release.
  branch=refs/tags/v0.0.1
gpg (GnuPG) 2.2.19
gpg: directory '/home/runner/.gnupg' created
gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
base64: invalid input
gpg: /home/runner/.gnupg/trustdb.gpg: trustdb created
gpg: key A6[33](https://github.com/ghostbuster91/scalafix-unified/runs/5079515519?check_suite_focus=true#step:4:33)84B42C7889C0: public key "scalafix-unified ci bot <kghost0@gmail.com>" imported
gpg: key A63384B42C7889C0: secret key imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg:       secret keys read: 1
gpg:   secret keys imported: 1
Tag push detected, publishing a stable release
```

I think that the script should fail if the `base64 -d` returns non-zero exit code.

https://github.com/sbt/sbt-ci-release/blob/main/plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala#L93

Currently, the exit code of the importing command is ignored. 
Notice, that piping multiple commands using `#|` operator will return only last command exit code which in our case is `gpg --import`.

I would be happy to submit a PR as soon as we agree upon the approach. 

Link to a github action build: https://github.com/ghostbuster91/scalafix-unified/runs/5079515519?check_suite_focus=true

**Comment by eed3si9n** [comment]
> Notice, that piping multiple commands using `#|` operator will return only last command exit code which in our case is `gpg --import`.

It is unfortunate that `#|` doesn't act in a `-o pipefail` way.

Maybe it could run

```scala
// running base64 alone to emulate pipefail
(s"echo $secret" #| "base64 --decode").!(...)
```

with a null ProcessLogger, which is something like `ProcessLogger(_ => ())`?
That way if base64 fails, it would be caught there.

**Comment by ghostbuster91** [comment]
> It is unfortunate that #| doesn't act in a -o pipefail way.

:100: 

> with a null ProcessLogger, which is something like ProcessLogger(_ => ())?
That way if base64 fails, it would be caught there.

I am not sure if I follow. Such null process logger would simply ignore all the errors, wouldn't it?
