### ISSUE TITLE
java.io.IOException: Supplied file ... is a not an existing directory!

### ISSUE THREAD

**Issue by paoloboni** [sbt/sbt-ci-release#234]
I see this problem was discussed in several other places, but none of the suggestions from other similar issues worked for me.

I'm hoping someone can help me understand what I'm doing wrong.

The project I'm trying to use this plugin with is a single module one, so with source directory in the root.

Link to the failure:
https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:130

Error stack trace:
```
java.io.IOException: Supplied file /home/runner/work/spray-json-derived-codecs/spray-json-derived-codecs/target/sonatype-staging/2.3.6 is a not an existing directory!
[131](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:131)
	at org.sonatype.spice.zapper.fs.AbstractDirectory.<init>(AbstractDirectory.java:32)
[132](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:132)
	at org.sonatype.spice.zapper.fs.DirectoryIOSource.<init>(DirectoryIOSource.java:68)
[133](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:133)
	at org.sonatype.spice.zapper.fs.DirectoryIOSource.<init>(DirectoryIOSource.java:59)
[134](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:134)
	at org.sonatype.spice.zapper.fs.DirectoryIOSource.<init>(DirectoryIOSource.java:50)
[135](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:135)
	at xerial.sbt.sonatype.SonatypeClient.$anonfun$uploadBundle$2(SonatypeClient.scala:284)
[136](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:136)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[137](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:137)
	at scala.util.Try$.apply(Try.scala:213)
[138](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:138)
	at wvlet.airframe.control.Retry$RetryContext.runInternal(Retry.scala:268)
[139](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:139)
	at wvlet.airframe.control.Retry$RetryContext.run(Retry.scala:253)
[140](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:140)
	at xerial.sbt.sonatype.SonatypeClient.uploadBundle(SonatypeClient.scala:269)
[141](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:141)
	at xerial.sbt.sonatype.SonatypeService.uploadBundle(SonatypeService.scala:73)
[142](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:142)
	at xerial.sbt.Sonatype$.$anonfun$sonatypeBundleRelease$2(Sonatype.scala:181)
[143](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:143)
	at xerial.sbt.Sonatype$.withSonatypeService(Sonatype.scala:437)
[144](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:144)
	at xerial.sbt.Sonatype$.$anonfun$sonatypeBundleRelease$1(Sonatype.scala:177)
[145](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:145)
	at scala.Option.getOrElse(Option.scala:189)
[146](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[147](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[148](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:148)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[149](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:149)
	at java.lang.reflect.Method.invoke(Method.java:498)
[150](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:150)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
[151](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:151)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
[152](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:152)
	at xsbt.boot.Launch$.run(Launch.scala:149)
[153](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:153)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
[154](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:154)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
[155](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:155)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
[156](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:156)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
[157](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:157)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
[158](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:158)
	at xsbt.boot.Boot$.run(Boot.scala:73)
[159](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:159)
	at xsbt.boot.Boot$.main(Boot.scala:21)
[160](https://github.com/paoloboni/spray-json-derived-codecs/runs/5640476753?check_suite_focus=true#step:4:160)
	at xsbt.boot.Boot.main(Boot.scala)  - (Sonatype.scala:443)
```

This is the directory structure I see in `target` (no `sonatype-staging`):
```
target
├── global-logging
├── sbt-sonatype-1180977470
├── scala-2.12
│   ├── api
│   ├── classes
│   ├── resolution-cache
│   ├── sync
│   ├── update
│   └── zinc
├── scala-2.13
│   ├── api
│   ├── classes
│   ├── resolution-cache
│   ├── sync
│   ├── test-classes
│   ├── update
│   └── zinc
├── scala-3.1.1
│   ├── api
│   ├── classes
│   ├── resolution-cache
│   ├── sync
│   ├── update
│   └── zinc
├── streams
│   ├── _global
│   └── compile
└── task-temp-directory
```

**Comment by paoloboni** [comment]
I tried adding `skip / publish := true` but that didn't help either: https://github.com/paoloboni/spray-json-derived-codecs/runs/5799437213?check_suite_focus=true
