### ISSUE TITLE
Publish stopped working: GPG failure in GitHub Actions

### ISSUE THREAD

**Issue by gzoller** [sbt/sbt-ci-release#297]
I have a mature project that I publish from time to time using sbt-ci-release (ver 1.5.11). I'm using GitHub Actions

Here is the publish portion of my yaml file:
```yaml
      - env:
          CI_SNAPSHOT_RELEASE: +publishSigned
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
        run: sbt ci-release
```

This has worked for a long time--from the Actions.  I have these variables all defined in secrets in GitHub, and haven't touched them. I've used the identical yaml code on a different project as recently as May 29, 2024 with zero issues--worked great.

Now all of the sudden on this project, when publish runs in my Action I get the output below. Note I don't call gpg directly myself--only whatever sbt-ci-release does.

Do you have any idea what this might be? I've got a package I'd really like to publish. Thanks for any help!

```
[info] gpg: no default secret key: No secret key
[info] gpg: signing failed: No secret key
[error] java.lang.RuntimeException: Failure running 'gpg --batch --pinentry-mode loopback --passphrase *** --detach-sign --armor --use-agent --output /home/runner/work/ScalaJack/ScalaJack/target/scala-3.4.2/scalajack-8.0.0.pom.asc /home/runner/work/ScalaJack/ScalaJack/target/scala-3.4.2/scalajack-8.0.0.pom'.  Exit code: 2
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at com.jsuereth.sbtpgp.CommandLineGpgSigner.sign(PgpSigner.scala:74)
[error] 	at com.jsuereth.sbtpgp.PgpSettings$.$anonfun$signingSettings$2(PgpSettings.scala:[151](https://github.com/gzoller/ScalaJack/actions/runs/9297315070/job/26214586975#step:7:152))
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:293)
[error] 	at scala.collection.immutable.Map$Map4.foreach(Map.scala:493)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:293)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:290)
[error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
[error] 	at com.jsuereth.sbtpgp.PgpSettings$.$anonfun$signingSettings$1(PgpSettings.scala:146)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] 	at sbt.Execute.work(Execute.scala:292)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:[158](https://github.com/gzoller/ScalaJack/actions/runs/9297315070/job/26214586975#step:7:159)3)
[error] (signedArtifacts) Failure running 'gpg --batch --pinentry-mode loopback --passphrase *** --detach-sign --armor --use-agent --output /home/runner/work/ScalaJack/ScalaJack/target/scala-3.4.2/scalajack-8.0.0.pom.asc /home/runner/work/ScalaJack/ScalaJack/target/scala-3.4.2/scalajack-8.0.0.pom'.  Exit code: 2
```

**Comment by gzoller** [comment]
Closing issue.  Pilot error on my part...sorry.  Project was mature all right... key expired!

**Comment by mkurz** [comment]
btw, latest version is 1.5.12
