### ISSUE TITLE
Issue publishing to oss.sonatype.org

### ISSUE THREAD

**Issue by ryanstull** [sbt/sbt-ci-release#299]
I'm trying to publish a new version of https://github.com/ryanstull/ScalaNullSafe, but I'm running into an issue:

```
...
[info] 	published scalanullsafe_2.13 to /home/runner/work/ScalaNullSafe/ScalaNullSafe/target/sonatype-staging/1.3.0/com/ryanstull/scalanullsafe_2.13/1.3.0/scalanullsafe_2.13-1.3.0.pom.asc
[info] 	published scalanullsafe_2.13 to /home/runner/work/ScalaNullSafe/ScalaNullSafe/target/sonatype-staging/1.3.0/com/ryanstull/scalanullsafe_2.13/1.3.0/scalanullsafe_2.13-1.3.0-sources.jar
[info] 	published scalanullsafe_2.13 to /home/runner/work/ScalaNullSafe/ScalaNullSafe/target/sonatype-staging/1.3.0/com/ryanstull/scalanullsafe_2.13/1.3.0/scalanullsafe_2.13-1.3.0.jar.asc
[info] 	published scalanullsafe_2.13 to /home/runner/work/ScalaNullSafe/ScalaNullSafe/target/sonatype-staging/1.3.0/com/ryanstull/scalanullsafe_2.13/1.3.0/scalanullsafe_2.13-1.3.0-sources.jar.asc
[info] 	published scalanullsafe_2.13 to /home/runner/work/ScalaNullSafe/ScalaNullSafe/target/sonatype-staging/1.3.0/com/ryanstull/scalanullsafe_2.13/1.3.0/scalanullsafe_2.13-1.3.0-javadoc.jar.asc
[info] 	published scalanullsafe_2.13 to /home/runner/work/ScalaNullSafe/ScalaNullSafe/target/sonatype-staging/1.3.0/com/ryanstull/scalanullsafe_2.13/1.3.0/scalanullsafe_2.13-1.3.0.jar
[info] 	published scalanullsafe_2.13 to /home/runner/work/ScalaNullSafe/ScalaNullSafe/target/sonatype-staging/1.3.0/com/ryanstull/scalanullsafe_2.13/1.3.0/scalanullsafe_2.13-1.3.0-javadoc.jar
[info] 	published scalanullsafe_2.13 to /home/runner/work/ScalaNullSafe/ScalaNullSafe/target/sonatype-staging/1.3.0/com/ryanstull/scalanullsafe_2.13/1.3.0/scalanullsafe_2.13-1.3.0.pom
[success] Total time: 16 s, completed Jun 29, 2024 9:22:51 PM
[info] Reapplying settings...
[info] set current project to ScalaNullSafe (in build file:/home/runner/work/ScalaNullSafe/ScalaNullSafe/)
2024-06-29 21:22:51.444Z  info [SonatypeService] sonatypeRepository  : https://oss.sonatype.org/service/local  - (SonatypeService.scala:26)
2024-06-29 21:22:51.446Z  info [SonatypeService] sonatypeProfileName : com.ryanstull  - (SonatypeService.scala:27)
[info] Preparing a new staging repository for [sbt-sonatype] ScalaNullSafe 1.3.0
2024-06-29 21:22:51.447Z  info [SonatypeClient] Reading staging repository profiles...  - (SonatypeClient.scala:117)
2024-06-29 21:22:52.682Z  info [SonatypeClient] Reading staging profiles...  - (SonatypeClient.scala:129)
2024-06-29 21:22:55.909Z  info [SonatypeClient] Creating a staging repository in profile com.ryanstull with a description key: [sbt-sonatype] ScalaNullSafe 1.3.0  - (SonatypeClient.scala:135)
2024-06-29 21:23:04.650Z  info [SonatypeClient] Created successfully: comryanstull-1044  - (SonatypeClient.scala:148)
2024-06-29 21:23:10.399Z  info [SonatypeService] Found a previous staging repository [comryanstull-1043] status:open, profile:com.ryanstull(9dd2c8b46008f8) description: [sbt-sonatype] ScalaNullSafe 1.3.0  - (SonatypeService.scala:103)
2024-06-29 21:23:10.399Z  info [SonatypeClient] Dropping staging repository [comryanstull-1043] status:open, profile:com.ryanstull(9dd2c8b46008f8) description: [sbt-sonatype] ScalaNullSafe 1.3.0  - (SonatypeClient.scala:238)
2024-06-29 21:23:10.835Z  info [SonatypeService] Dropped successfully: comryanstull-1043  - (SonatypeService.scala:175)
2024-06-29 21:23:10.893Z  info [SonatypeClient] Uploading bundle /home/runner/work/ScalaNullSafe/ScalaNullSafe/target/sonatype-staging/1.3.0 to https://oss.sonatype.org/service/local/staging/deployByRepositoryId/comryanstull-1044/  - (SonatypeClient.scala:297)
2024-06-29 21:23:10.996Z error [Sonatype] 
java.io.IOException: Failure:java.util.concurrent.ExecutionException: java.io.IOException: Unexpected server response: 401 Content access is protected by token
	at org.sonatype.spice.zapper.internal.transport.AbstractChargerClient.doUpload(AbstractChargerClient.java:65)
	at org.sonatype.spice.zapper.internal.transport.AbstractClient.upload(AbstractClient.java:104)
	at org.sonatype.spice.zapper.internal.transport.AbstractClient.upload(AbstractClient.java:61)
	at xerial.sbt.sonatype.SonatypeClient.$anonfun$uploadBundle$2(SonatypeClient.scala:298)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at wvlet.airframe.control.Retry$RetryContext.runInternal(Retry.scala:269)
	at wvlet.airframe.control.Retry$RetryContext.run(Retry.scala:254)
	at xerial.sbt.sonatype.SonatypeClient.uploadBundle(SonatypeClient.scala:278)
	at xerial.sbt.sonatype.SonatypeService.uploadBundle(SonatypeService.scala:73)
	at xerial.sbt.Sonatype$.$anonfun$sonatypeBundleRelease$2(Sonatype.scala:181)
	at xerial.sbt.Sonatype$.withSonatypeService(Sonatype.scala:437)
	at xerial.sbt.Sonatype$.$anonfun$sonatypeBundleRelease$1(Sonatype.scala:177)
	at scala.Option.getOrElse(Option.scala:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Unexpected server response: 401 Content access is protected by token
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.sonatype.spice.zapper.internal.transport.AbstractChargerClient.doUpload(AbstractChargerClient.java:61)
	... 53 more
Caused by: java.io.IOException: Unexpected server response: 401 Content access is protected by token
	at org.sonatype.spice.zapper.client.hc4.Hc4Client.upload(Hc4Client.java:107)
	at org.sonatype.spice.zapper.client.hc4.Hc4Track.call(Hc4Track.java:38)
	at org.sonatype.spice.zapper.client.hc4.Hc4Track.call(Hc4Track.java:23)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)  - (Sonatype.scala:443)

Error: Process completed with exit code 1.
##[debug]Finishing: Run sbt ci-release
```

I never got this error before.  It seems like it's expecting a token even though I'm providing my sonatype username and password. 🤔  Any help would be appreciated.

**Comment by ryanstull** [comment]
I figured out and fixed the issue.  I had to switch to token based auth instead of using my sonatype username and password, then it worked.

https://support.sonatype.com/hc/en-us/articles/360049469534-401-Content-access-is-protected-by-token-when-accessing-repositories

For those who publish to oss.sonatype.org you can go to https://oss.sonatype.org/#profile;User%20Token to get your auth token username and password

**Comment by hagay3** [comment]
@ryanstull 
With the new s01 server the site address is a bit different
https://s01.oss.sonatype.org/#profile;User%20Token
